#ifndef _HWSETUP_H_INCLUDED_
#define _HWSETUP_H_INCLUDED_

#define DALLAS_SENSOR_DATA_PIN 22
#define MAX_DALLAS_SENSORS 8




#define HW_FEEDER_CTRL_PIN A10
#define HW_ENCODER_PINA 15
#define HW_ENCODER_PINB 18
#define HW_ENCODER_PINBTN 34
#define HW_DISPLAY_PIN 1
#define HW_ZERO_DETECT_PIN 2
#define HW_BLOWER_CTRL_PIN 32

#define HW_PUMP_CO1_CTRL_PIN  A9
#define HW_PUMP_CWU1_CTRL_PIN  A15
#define HW_PUMP_CO2_CTRL_PIN  A14
#define HW_PUMP_CIRC_CTRL_PIN  A8
#define HW_THERMOSTAT_PIN 47
#define HW_THERMOSTAT_PIN_ALT 26

#define MAX6675_0_SCK_PIN 39
#define MAX6675_0_CS_PIN 41
#define MAX6675_0_SO_PIN 40

#define MAX6675_1_SCK_PIN 0 //disable
#define MAX6675_1_CS_PIN 44
#define MAX6675_1_SO_PIN 46


#define DISPLAY_TEXT_LINES 2
#define DISPLAY_TEXT_LEN  16

#define MPIEC_ENABLE_WEBSERVER
//#define MPIEC_ENABLE_SCRIPT

#endif
