set RRDTOOL=C:\tools\rrdtool\rrdtool.exe
set DF=data.rrd

%RRDTOOL% graph fuel.gif -s %1 -e %2 ^
	DEF:TCO=%DF%:TCO:AVERAGE ^
	DEF:TCWU=%DF%:TCWU:AVERAGE ^
	DEF:TRET=%DF%:TRET:AVERAGE ^
	DEF:TEXH=%DF%:TEXH:AVERAGE ^
	DEF:FLOWN=%DF%:FLOWN:AVERAGE ^
	DEF:NEEDH=%DF%:NEEDH:AVERAGE ^
	DEF:FEEDMS=%DF%:FEEDMS:AVERAGE ^
	CDEF:FLOW10=FLOWN,10,/ ^
	CDEF:FEEDG=FEEDMS,1000,/,STEPWIDTH,* ^
	CDEF:FEEDS=FEEDMS,1000,/ ^
	CDEF:FEEDKG=FEEDMS,1000,/,2.77,*,1000,/ ^
	VDEF:FEEDTOT=FEEDKG,TOTAL ^
	LINE2:FEEDG#FF3020:FEED ^
	TICK:NEEDH#CC405025:-0.1:H ^
	GPRINT:FEEDTOT:%%2.3lf ^
	-h 600 -w 1800