set RRDTOOL=C:\tools\rrdtool\rrdtool.exe
set DF=data.rrd

%RRDTOOL% graph out.gif -s %1 -e %2 ^
	DEF:TCO=%DF%:TCO:AVERAGE ^
	DEF:TCWU=%DF%:TCWU:AVERAGE ^
	DEF:TRET=%DF%:TRET:AVERAGE ^
	DEF:TEXH=%DF%:TEXH:AVERAGE ^
	DEF:FLOWN=%DF%:FLOWN:AVERAGE ^
	DEF:NEEDH=%DF%:NEEDH:AVERAGE ^
	CDEF:FLOW10=FLOWN,10,/ ^
	LINE2:TCO#FF3020:CO ^
	LINE2:TCWU#CC8080:CWU ^
	LINE2:TRET#BACA50:Powr ^
	LINE2:TEXH#901090:Spaliny ^
	LINE1:FLOW10#2030FF:Flow ^
	TICK:NEEDH#CC405025:-0.1:H ^
	-h 600 -w 1800